[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# dd if=target/x86_64-unknown-none/debug/bootimage-sigmaos.bin

[build]
target = "x86_64-unknown-none.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
